[package]
name = "arkforge-standalone"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
arkforge-artifact = { path = "../arkforge-artifact" }
arkforge-client = { path = "../arkforge-client" }
arkforge-core = { path = "../arkforge-core" }
arkforge-authority-api = { path = "../arkforge-authority-api" }
arkforge-ipc = { path = "../arkforge-ipc" }
arkforge-platform = { path = "../arkforge-platform" }
arkforge-transport = { path = "../arkforge-transport" }
arkforged = { path = "../arkforged" }
